// Fetches 10y of OHLC data for the trading game asset universe from Yahoo Finance.
// Output: src/data/marketHistory.ts — a typed bundle the app reads at runtime, no network calls.
// Run: npx tsx scripts/fetch-history.ts
import YahooFinance from 'yahoo-finance2';
import fs from 'node:fs';
import path from 'node:path';

const yahooFinance = new (YahooFinance as unknown as new () => any)();

const TICKERS = ['VTI', 'BND', 'VXUS', 'AAPL', 'NVDA', 'TSLA', 'GOOGL', 'COIN'] as const;

const META: Record<string, { name: string; flavor: string; risk: 'low' | 'mid' | 'high' }> = {
  VTI: { name: 'Total US Market', flavor: 'The whole pie. Boring is beautiful.', risk: 'mid' },
  BND: { name: 'US Bonds', flavor: 'Steady. Slow. Sleeps well.', risk: 'low' },
  VXUS: { name: 'International', flavor: 'Earth minus the US.', risk: 'mid' },
  AAPL: { name: 'Apple', flavor: 'The iPhone money printer.', risk: 'mid' },
  NVDA: { name: 'NVIDIA', flavor: 'AI chip rocket. Volatile.', risk: 'high' },
  TSLA: { name: 'Tesla', flavor: 'Cars, drama, vibes.', risk: 'high' },
  GOOGL: { name: 'Alphabet', flavor: 'Search + ads + everything else.', risk: 'mid' },
  COIN: { name: 'Coinbase', flavor: 'Crypto exposure. Buckle up.', risk: 'high' },
};

interface PricePoint {
  date: string; // YYYY-MM-DD
  close: number;
}

interface TickerSeries {
  symbol: string;
  name: string;
  flavor: string;
  risk: 'low' | 'mid' | 'high';
  monthly: PricePoint[];
  weekly: PricePoint[];
}

async function fetchSeries(symbol: string, interval: '1mo' | '1wk'): Promise<PricePoint[]> {
  const period1 = new Date();
  period1.setFullYear(period1.getFullYear() - 10);

  const result = await yahooFinance.chart(symbol, {
    period1,
    interval,
  });
  const quotes = result.quotes ?? [];
  return quotes
    .filter((q) => q.close != null && q.date != null)
    .map((q) => ({
      date: new Date(q.date as Date).toISOString().slice(0, 10),
      close: Number((q.close as number).toFixed(2)),
    }));
}

async function run() {
  const out: TickerSeries[] = [];
  for (const symbol of TICKERS) {
    process.stdout.write(`fetching ${symbol}…`);
    try {
      const monthly = await fetchSeries(symbol, '1mo');
      const weekly = await fetchSeries(symbol, '1wk');
      out.push({
        symbol,
        name: META[symbol].name,
        flavor: META[symbol].flavor,
        risk: META[symbol].risk,
        monthly,
        weekly,
      });
      process.stdout.write(` ok (${monthly.length}mo / ${weekly.length}wk)\n`);
    } catch (err) {
      console.error(` FAILED:`, err instanceof Error ? err.message : err);
      process.exit(1);
    }
  }

  const header = `// Auto-generated by scripts/fetch-history.ts on ${new Date().toISOString()}
// Do not edit by hand. Re-run with: npx tsx scripts/fetch-history.ts
export type Risk = 'low' | 'mid' | 'high';
export interface PricePoint { date: string; close: number }
export interface TickerSeries {
  symbol: string;
  name: string;
  flavor: string;
  risk: Risk;
  monthly: PricePoint[];
  weekly: PricePoint[];
}

export const marketHistory: TickerSeries[] = `;

  const body = JSON.stringify(out, null, 2);
  const outPath = path.join(__dirname, '..', 'src', 'data', 'marketHistory.ts');
  fs.writeFileSync(outPath, header + body + ';\n', 'utf-8');
  console.log(`\n✓ wrote ${outPath}`);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
